id: I5000A708
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T01:57:22+00:00'
last_modified: '2022-06-16T06:22:23.078229+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS16692
  title: རྡོ་རྗེ་སེམས་དཔའ་ཐུགས་ཀྱིས་སྒྲུབ་པའི་བསྙེན་སྒྲུབ་ཆོ་ག་རྣམ་གྲོལ་ལམ་བཟང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    76C6:
      image_group_id: I8LS16711
      title: ''
      total_pages: 134
      order: 1
      base_file: 76C6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
